/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`agenda` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `agenda`;

/*Table structure for table `pessoa` */

DROP TABLE IF EXISTS `pessoa`;

CREATE TABLE `pessoa` (
  `ID` varchar(40) NOT NULL,
  `NOME` varchar(255) DEFAULT NULL,
  `SOBRE_NOME` varchar(255) DEFAULT NULL,
  `DATA_NASCIMENTO` datetime DEFAULT NULL,
  `DATA_CADASTRO` datetime DEFAULT NULL,
  `GENERO` char(1) DEFAULT NULL,
  `RELACIONAMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `pessoacontato` */

DROP TABLE IF EXISTS `pessoacontato`;

CREATE TABLE `pessoacontato` (
  `ID` varchar(40) NOT NULL,
  `TELEFONE` varchar(255) DEFAULT NULL,
  `TIPO_TELEFONE` int(11) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `TIPO_EMAIL` int(11) DEFAULT NULL,
  `PESSOA_ID` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PESSOA_ID` (`PESSOA_ID`),
  CONSTRAINT `FK916446353BE7574B` FOREIGN KEY (`PESSOA_ID`) REFERENCES `pessoa` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `pessoaendereco` */

DROP TABLE IF EXISTS `pessoaendereco`;

CREATE TABLE `pessoaendereco` (
  `ID` varchar(40) NOT NULL,
  `ENDERECO` varchar(255) DEFAULT NULL,
  `TIPO_ENDERECO` int(11) DEFAULT NULL,
  `CEP` varchar(255) DEFAULT NULL,
  `CIDADE` varchar(255) DEFAULT NULL,
  `BAIRRO` varchar(255) DEFAULT NULL,
  `ESTADO` varchar(255) DEFAULT NULL,
  `PAIS` varchar(255) DEFAULT NULL,
  `PESSOA_ID` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PESSOA_ID` (`PESSOA_ID`),
  CONSTRAINT `FKFA4EB57C3BE7574B` FOREIGN KEY (`PESSOA_ID`) REFERENCES `pessoa` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
